[package.image]
versions = ["0.24"]
use_default_features = true
features = []

[package.nalgebra]
versions = ["0.32"]
use_default_features = true
features = []

[package.opencv]
versions = ["0.81.5"]
use_default_features = false
features = ["calib3d"]

[package.ndarray]
versions = ["0.15"]
use_default_features = true
features = []

[package.tch]
versions = ["0.13"]
use_default_features = true
features = []

[package.imageproc]
versions = ["0.23"]
use_default_features = true
features = []
